// ==========================================================================
// 📖 华文智能互动学习阅读器 - 词汇数据库 (data.js)
// ==========================================================================

const lessonTitle = "顶碗少年";

const lessonData = [
    // ===== 第1段 =====
    ["有些", "yǒu xiē", "some", "sesetengah"],
    ["偶然", "ǒu rán", "accidental", "kebetulan"],
    ["遇到", "yù dào", "encounter", "menemui"],
    ["的", "de", "", ""],
    ["小", "xiǎo", "small", "kecil"],
    ["事情", "shì qíng", "things", "perkara"],
    ["，", "", "", ""],
    ["竟", "jìng", "unexpectedly", "sebenarnya"],
    ["会", "huì", "will", "akan"],
    ["难以忘怀", "nán yǐ wàng huái", "hard to forget", "sukar dilupakan"],
    ["，", "", "", ""],
    ["并且", "bìng qiě", "and", "dan"],
    ["时时", "shí shí", "always", "sentiasa"],
    ["萦绕", "yíng rào", "linger", "berlegar"],
    ["于", "yú", "in", "di"],
    ["心", "xīn", "heart", "hati"],
    ["。", "", "", ""],
    ["因为", "yīn wèi", "because", "kerana"],
    ["，", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["或许", "huò xǔ", "perhaps", "mungkin"],
    ["能", "néng", "can", "boleh"],
    ["从", "cóng", "from", "daripada"],
    ["中", "zhōng", "in", "dalam"],
    ["不断", "bù duàn", "continuously", "sentiasa"],
    ["地", "de", "", ""],
    ["得到", "dé dào", "gain", "mendapat"],
    ["启示", "qǐ shì", "inspiration", "inspirasi"],
    ["，", "", "", ""],
    ["悟出", "wù chū", "realize", "menyedari"],
    ["一些", "yī xiē", "some", "sesetengah"],
    ["人生", "rén shēng", "life", "kehidupan"],
    ["的", "de", "", ""],
    ["哲理", "zhé lǐ", "philosophy", "falsafah"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第2段

    // ===== 第2段 =====
    ["这是", "zhè shì", "This is", "Ini adalah"],
    ["二十多年", "èr shí duō nián", "more than twenty years", "lebih dua puluh tahun"],
    ["前", "qián", "ago", "dahulu"],
    ["的", "de", "", ""],
    ["事情", "shì qíng", "matter", "perkara"],
    ["了", "le", "", ""],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第3段

    // ===== 第3段 =====
    ["有一次", "yǒu yī cì", "once", "satu kali"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["在", "zài", "at", "di"],
    ["上海", "shàng hǎi", "Shanghai", "Shanghai"],
    ["大世界", "dà shì jiè", "Great World", "Great World"],
    ["的", "de", "", ""],
    ["露天", "lù tiān", "open-air", "terbuka"],
    ["剧场", "jù chǎng", "theater", "teater"],
    ["里", "lǐ", "in", "dalam"],
    ["看", "kàn", "watch", "menonton"],
    ["杂技", "zá jì", "acrobatics", "akrobatik"],
    ["表演", "biǎo yǎn", "performance", "persembahan"],
    ["，", "", "", ""],
    ["节目", "jié mù", "program", "program"],
    ["很", "hěn", "very", "sangat"],
    ["精彩", "jīng cǎi", "wonderful", "hebat"],
    ["，", "", "", ""],
    ["场内", "chǎng nèi", "inside", "di dalam"],
    ["座无虚席", "zuò wú xū xí", "packed", "penuh sesak"],
    ["。", "", "", ""],
    ["坐在", "zuò zài", "sitting at", "duduk di"],
    ["前几排", "qián jǐ pái", "front rows", "barisan hadapan"],
    ["的", "de", "", ""],
    ["，", "", "", ""],
    ["全是", "quán shì", "all are", "semuanya"],
    ["来自", "lái zì", "from", "daripada"],
    ["异国", "yì guó", "foreign country", "negara asing"],
    ["的", "de", "", ""],
    ["旅游者", "lǚ yóu zhě", "tourists", "pelancong"],
    ["。", "", "", ""],
    ["优美", "yōu měi", "graceful", "anggun"],
    ["的", "de", "", ""],
    ["东方", "dōng fāng", "Oriental", "Timur"],
    ["杂技", "zá jì", "acrobatics", "akrobatik"],
    ["，", "", "", ""],
    ["使", "shǐ", "make", "membuat"],
    ["他们", "tā men", "them", "mereka"],
    ["入迷", "rù mí", "fascinated", "terpesona"],
    ["了", "le", "", ""],
    ["。", "", "", ""],
    ["他们", "tā men", "they", "mereka"],
    ["和", "hé", "and", "dan"],
    ["中国", "zhōng guó", "Chinese", "China"],
    ["观众", "guān zhòng", "audience", "penonton"],
    ["一起", "yī qǐ", "together", "bersama"],
    ["，", "", "", ""],
    ["为", "wèi", "for", "untuk"],
    ["每一个", "měi yī gè", "every", "setiap"],
    ["节目", "jié mù", "program", "program"],
    ["喝彩", "hè cǎi", "cheer", "bersorak"],
    ["鼓掌", "gǔ zhǎng", "applaud", "bertepuk tangan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第4段

    // ===== 第4段 =====
    ["一位", "yī wèi", "a", "seorang"],
    ["英俊", "yīng jùn", "handsome", "kacak"],
    ["的", "de", "", ""],
    ["少年", "shào nián", "youth", "remaja"],
    ["出场", "chū chǎng", "appear", "muncul"],
    ["了", "le", "", ""],
    ["。", "", "", ""],
    ["在", "zài", "in", "dalam"],
    ["轻松", "qīng sōng", "relaxed", "santai"],
    ["优雅", "yōu yǎ", "elegant", "anggun"],
    ["的", "de", "", ""],
    ["乐曲", "yuè qǔ", "music", "muzik"],
    ["声", "shēng", "sound", "bunyi"],
    ["里", "lǐ", "in", "dalam"],
    ["，", "", "", ""],
    ["只见", "zhǐ jiàn", "only see", "hanya melihat"],
    ["他", "tā", "he", "dia"],
    ["头上", "tóu shàng", "on head", "di atas kepala"],
    ["顶着", "dǐng zhe", "balance on head", "menjunjung"],
    ["高高", "gāo gāo", "high", "tinggi"],
    ["的", "de", "", ""],
    ["一叠", "yī dié", "a stack", "setimbun"],
    ["金边", "jīn biān", "gold-rimmed", "bertepi emas"],
    ["红花", "hóng huā", "red flower", "bunga merah"],
    ["白瓷碗", "bái cí wǎn", "white porcelain bowls", "mangkuk porselin putih"],
    ["，", "", "", ""],
    ["柔软", "róu ruǎn", "soft", "lembut"],
    ["而", "ér", "and", "dan"],
    ["自然", "zì rán", "natural", "semula jadi"],
    ["地", "de", "", ""],
    ["舒展", "shū zhǎn", "stretch", "meregang"],
    ["着", "zhe", "", ""],
    ["肢体", "zhī tǐ", "body", "anggota badan"],
    ["，", "", "", ""],
    ["做出", "zuò chū", "make", "membuat"],
    ["各种各样", "gè zhǒng gè yàng", "various", "pelbagai"],
    ["令人", "lìng rén", "make people", "membuat orang"],
    ["惊羡", "jīng xiàn", "admire", "kagum"],
    ["的", "de", "", ""],
    ["动作", "dòng zuò", "movements", "gerakan"],
    ["，", "", "", ""],
    ["忽而", "hū ér", "now", "kadang-kadang"],
    ["卧倒", "wò dǎo", "lie down", "berbaring"],
    ["，", "", "", ""],
    ["忽而", "hū ér", "now", "kadang-kadang"],
    ["跃起", "yuè qǐ", "jump up", "melompat"],
    ["……", "", "", ""],

    ["\n", "", "", ""], // 👈 第5段

    // ===== 第5段 =====
    ["碗", "wǎn", "bowls", "mangkuk"],
    ["，", "", "", ""],
    ["在", "zài", "on", "di"],
    ["他", "tā", "his", "dia"],
    ["的", "de", "", ""],
    ["头顶", "tóu dǐng", "top of head", "atas kepala"],
    ["摇摇晃晃", "yáo yáo huàng huàng", "wobbling", "bergoyang-goyang"],
    ["，", "", "", ""],
    ["却", "què", "but", "tetapi"],
    ["总是", "zǒng shì", "always", "sentiasa"],
    ["不", "bù", "not", "tidak"],
    ["掉下来", "diào xià lái", "fall down", "jatuh"],
    ["。", "", "", ""],
    ["最后", "zuì hòu", "finally", "akhirnya"],
    ["，", "", "", ""],
    ["是", "shì", "is", "ialah"],
    ["一组", "yī zǔ", "a set", "satu set"],
    ["难度", "nán dù", "difficulty", "kesukaran"],
    ["较大", "jiào dà", "relatively large", "agak besar"],
    ["的", "de", "", ""],
    ["动作", "dòng zuò", "movements", "gerakan"],
    ["——", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["骑", "qí", "ride", "menunggang"],
    ["在", "zài", "on", "di"],
    ["另一位", "lìng yī wèi", "another", "seorang lagi"],
    ["演员", "yǎn yuán", "performer", "pelakon"],
    ["身上", "shēn shàng", "body", "badan"],
    ["，", "", "", ""],
    ["两个人", "liǎng gè rén", "two people", "dua orang"],
    ["一会儿", "yī huì ér", "a while", "sekejap"],
    ["站起", "zhàn qǐ", "stand up", "berdiri"],
    ["，", "", "", ""],
    ["一会儿", "yī huì ér", "a while", "sekejap"],
    ["躺下", "tǎng xià", "lie down", "berbaring"],
    ["，", "", "", ""],
    ["一会儿", "yī huì ér", "a while", "sekejap"],
    ["用", "yòng", "use", "menggunakan"],
    ["各种", "gè zhǒng", "various", "pelbagai"],
    ["姿态", "zī tài", "posture", "gaya"],
    ["转动", "zhuàn dòng", "turn", "berputar"],
    ["着", "zhe", "", ""],
    ["身躯", "shēn qū", "body", "tubuh"],
    ["。", "", "", ""],
    ["站在", "zhàn zài", "standing on", "berdiri di"],
    ["别人", "bié rén", "others", "orang lain"],
    ["晃动", "huàng dòng", "shaking", "bergoyang"],
    ["着", "zhe", "", ""],
    ["的", "de", "", ""],
    ["身体", "shēn tǐ", "body", "badan"],
    ["上", "shàng", "on", "atas"],
    ["，", "", "", ""],
    ["很难", "hěn nán", "very hard", "sangat sukar"],
    ["再", "zài", "again", "lagi"],
    ["保持", "bǎo chí", "maintain", "mengekalkan"],
    ["平衡", "píng héng", "balance", "keseimbangan"],
    ["，", "", "", ""],
    ["他", "tā", "his", "dia"],
    ["头顶", "tóu dǐng", "top of head", "atas kepala"],
    ["上", "shàng", "on", "atas"],
    ["的", "de", "", ""],
    ["碗", "wǎn", "bowls", "mangkuk"],
    ["，", "", "", ""],
    ["摇晃", "yáo huàng", "shake", "bergoyang"],
    ["得", "de", "", ""],
    ["厉害", "lì hài", "severely", "teruk"],
    ["起来", "qǐ lái", "up", "naik"],
    ["。", "", "", ""],
    ["在", "zài", "in", "dalam"],
    ["一个", "yī gè", "a", "satu"],
    ["大幅度", "dà fú dù", "large amplitude", "amplitud besar"],
    ["转身", "zhuǎn shēn", "turn around", "berpaling"],
    ["的", "de", "", ""],
    ["刹那间", "chà nà jiān", "in an instant", "sekelip mata"],
    ["，", "", "", ""],
    ["那", "nà", "that", "itu"],
    ["一大摞", "yī dà luò", "a large stack", "setimbun besar"],
    ["碗", "wǎn", "bowls", "mangkuk"],
    ["突然", "tū rán", "suddenly", "tiba-tiba"],
    ["从", "cóng", "from", "dari"],
    ["他", "tā", "his", "dia"],
    ["头上", "tóu shàng", "head", "kepala"],
    ["掉了下来", "diào le xià lái", "fell down", "jatuh"],
    ["！", "", "", ""],

    ["\n", "", "", ""], // 👈 第6段

    // ===== 第6段 =====
    ["这", "zhè", "This", "Ini"],
    ["意想不到", "yì xiǎng bù dào", "unexpected", "tidak disangka"],
    ["的", "de", "", ""],
    ["失误", "shī wù", "mistake", "kesilapan"],
    ["，", "", "", ""],
    ["让", "ràng", "make", "membuat"],
    ["所有", "suǒ yǒu", "all", "semua"],
    ["的", "de", "", ""],
    ["观众", "guān zhòng", "audience", "penonton"],
    ["都", "dōu", "all", "semua"],
    ["惊呆了", "jīng dāi le", "stunned", "terkejut"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第7段

    // ===== 第7段 =====
    ["台上", "tái shàng", "on stage", "di atas pentas"],
    ["并没有", "bìng méi yǒu", "did not", "tidak"],
    ["慌乱", "huāng luàn", "panic", "kelam-kabut"],
    ["。", "", "", ""],
    ["顶碗", "dǐng wǎn", "bowl balancing", "menjunjung mangkuk"],
    ["的", "de", "", ""],
    ["少年", "shào nián", "youth", "remaja"],
    ["歉疚", "qiàn jiù", "apologetic", "rasa bersalah"],
    ["地", "de", "", ""],
    ["微笑", "wēi xiào", "smile", "senyum"],
    ["着", "zhe", "", ""],
    ["，", "", "", ""],
    ["不失风度", "bù shī fēng dù", "not lose grace", "tidak hilang gaya"],
    ["地", "de", "", ""],
    ["向", "xiàng", "to", "kepada"],
    ["观众", "guān zhòng", "audience", "penonton"],
    ["鞠了", "jū le", "bowed", "tunduk"],
    ["一躬", "yī gōng", "a bow", "satu tunduk"],
    ["。", "", "", ""],
    ["一位", "yī wèi", "a", "seorang"],
    ["姑娘", "gū niáng", "girl", "gadis"],
    ["走", "zǒu", "walk", "berjalan"],
    ["出来", "chū lái", "out", "keluar"],
    ["，", "", "", ""],
    ["扫起", "sǎo qǐ", "sweep up", "menyapu"],
    ["了", "le", "", ""],
    ["地上", "dì shàng", "ground", "tanah"],
    ["的", "de", "", ""],
    ["碎瓷片", "suì cí piàn", "broken porcelain pieces", "serpihan porselin"],
    ["，", "", "", ""],
    ["又", "yòu", "again", "lagi"],
    ["捧出", "pěng chū", "carry out", "membawa keluar"],
    ["一大摞", "yī dà luò", "a large stack", "setimbun besar"],
    ["碗", "wǎn", "bowls", "mangkuk"],
    ["，", "", "", ""],
    ["还是", "hái shì", "still", "masih"],
    ["金边", "jīn biān", "gold-rimmed", "bertepi emas"],
    ["红花", "hóng huā", "red flower", "bunga merah"],
    ["白瓷碗", "bái cí wǎn", "white porcelain bowls", "mangkuk porselin putih"],
    ["，", "", "", ""],
    ["整整", "zhěng zhěng", "exactly", "tepat"],
    ["十只", "shí zhī", "ten", "sepuluh"],
    ["，", "", "", ""],
    ["一只", "yī zhī", "one", "satu"],
    ["不少", "bù shǎo", "not less", "tidak kurang"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第8段

    // ===== 第8段 =====
    ["于是", "yú shì", "so", "maka"],
    ["，", "", "", ""],
    ["音乐", "yīn yuè", "music", "muzik"],
    ["又", "yòu", "again", "lagi"],
    ["响", "xiǎng", "sound", "berbunyi"],
    ["起来", "qǐ lái", "up", "naik"],
    ["，", "", "", ""],
    ["碗", "wǎn", "bowls", "mangkuk"],
    ["又", "yòu", "again", "lagi"],
    ["高高", "gāo gāo", "high", "tinggi"],
    ["地", "de", "", ""],
    ["顶", "dǐng", "balance", "junjung"],
    ["在", "zài", "on", "di"],
    ["了", "le", "", ""],
    ["少年", "shào nián", "youth", "remaja"],
    ["头上", "tóu shàng", "head", "kepala"],
    ["。", "", "", ""],
    ["少年", "shào nián", "youth", "remaja"],
    ["沉着", "chén zhuó", "calmly", "tenang"],
    ["地", "de", "", ""],
    ["重复", "chóng fù", "repeat", "ulang"],
    ["着", "zhe", "", ""],
    ["刚才", "gāng cái", "just now", "tadi"],
    ["的", "de", "", ""],
    ["动作", "dòng zuò", "movements", "gerakan"],
    ["，", "", "", ""],
    ["依然", "yī rán", "still", "masih"],
    ["是", "shì", "is", "ialah"],
    ["那么", "nà me", "so", "begitu"],
    ["轻松", "qīng sōng", "relaxed", "santai"],
    ["优美", "yōu měi", "graceful", "anggun"],
    ["，", "", "", ""],
    ["紧张不安", "jǐn zhāng bù ān", "nervous", "gelisah"],
    ["的", "de", "", ""],
    ["观众", "guān zhòng", "audience", "penonton"],
    ["终于", "zhōng yú", "finally", "akhirnya"],
    ["又", "yòu", "again", "lagi"],
    ["陶醉", "táo zuì", "intoxicated", "terpesona"],
    ["在", "zài", "in", "di"],
    ["他", "tā", "his", "dia"],
    ["的", "de", "", ""],
    ["表演", "biǎo yǎn", "performance", "persembahan"],
    ["之中", "zhī zhōng", "in", "di dalam"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第9段

    // ===== 第9段 =====
    ["到", "dào", "to", "ke"],
    ["最后关头", "zuì hòu guān tóu", "final moment", "saat akhir"],
    ["了", "le", "", ""],
    ["，", "", "", ""],
    ["又是", "yòu shì", "again", "lagi"],
    ["两个人", "liǎng gè rén", "two people", "dua orang"],
    ["叠", "dié", "stack", "bertindih"],
    ["在一起", "zài yī qǐ", "together", "bersama"],
    ["，", "", "", ""],
    ["又是", "yòu shì", "again", "lagi"],
    ["一个", "yī gè", "one", "satu"],
    ["接", "jiē", "follow", "sambung"],
    ["一个", "yī gè", "one", "satu"],
    ["艰难", "jiān nán", "difficult", "sukar"],
    ["的", "de", "", ""],
    ["转身", "zhuǎn shēn", "turn", "berpaling"],
    ["，", "", "", ""],
    ["碗", "wǎn", "bowls", "mangkuk"],
    ["，", "", "", ""],
    ["又", "yòu", "again", "lagi"],
    ["在", "zài", "on", "di"],
    ["他", "tā", "his", "dia"],
    ["头顶", "tóu dǐng", "top of head", "atas kepala"],
    ["厉害", "lì hài", "severely", "teruk"],
    ["地", "de", "", ""],
    ["摇晃", "yáo huàng", "shake", "bergoyang"],
    ["起来", "qǐ lái", "up", "naik"],
    ["。", "", "", ""],
    ["观众", "guān zhòng", "audience", "penonton"],
    ["们", "men", "", ""],
    ["屏着气", "bǐng zhe qì", "hold breath", "tahan nafas"],
    ["，", "", "", ""],
    ["目不转睛", "mù bù zhuǎn jīng", "gaze fixedly", "memandang tanpa berkelip"],
    ["地", "de", "", ""],
    ["盯着", "dīng zhe", "stare at", "memerhatikan"],
    ["他", "tā", "his", "dia"],
    ["头上", "tóu shàng", "head", "kepala"],
    ["的", "de", "", ""],
    ["碗", "wǎn", "bowls", "mangkuk"],
    ["……", "", "", ""],
    ["眼看", "yǎn kàn", "see", "melihat"],
    ["身体", "shēn tǐ", "body", "badan"],
    ["已经", "yǐ jīng", "already", "sudah"],
    ["转过来", "zhuǎn guò lái", "turned around", "berpaling"],
    ["了", "le", "", ""],
    ["，", "", "", ""],
    ["几个", "jǐ gè", "several", "beberapa"],
    ["性急", "xìng jí", "impatient", "tidak sabar"],
    ["的", "de", "", ""],
    ["外国", "wài guó", "foreign", "asing"],
    ["观众", "guān zhòng", "audience", "penonton"],
    ["忍不住", "rěn bù zhù", "cannot help", "tidak dapat menahan"],
    ["拍响", "pāi xiǎng", "clap", "bertepuk"],
    ["了", "le", "", ""],
    ["巴掌", "bā zhǎng", "palms", "tapak tangan"],
    ["。", "", "", ""],
    ["那", "nà", "that", "itu"],
    ["一摞", "yī luò", "a stack", "setimbun"],
    ["碗", "wǎn", "bowls", "mangkuk"],
    ["却", "què", "but", "tetapi"],
    ["仿佛", "fǎng fú", "as if", "seolah-olah"],
    ["故意", "gù yì", "deliberately", "sengaja"],
    ["捣蛋", "dǎo dàn", "make trouble", "buat kacau"],
    ["，", "", "", ""],
    ["突然", "tū rán", "suddenly", "tiba-tiba"],
    ["跳起", "tiào qǐ", "jump up", "melompat"],
    ["摇摆舞", "yáo bǎi wǔ", "swing dance", "tarian goyang"],
    ["来", "lái", "come", "datang"],
    ["。", "", "", ""],
    ["少年", "shào nián", "youth", "remaja"],
    ["急忙", "jí máng", "hurriedly", "segera"],
    ["晃动", "huàng dòng", "shake", "menggoncang"],
    ["脑袋", "nǎo dai", "head", "kepala"],
    ["保持", "bǎo chí", "maintain", "mengekalkan"],
    ["平衡", "píng héng", "balance", "keseimbangan"],
    ["，", "", "", ""],
    ["可是", "kě shì", "but", "tetapi"],
    ["来不及", "lái bù jí", "too late", "terlambat"],
    ["了", "le", "", ""],
    ["。", "", "", ""],
    ["碗", "wǎn", "bowls", "mangkuk"],
    ["，", "", "", ""],
    ["又", "yòu", "again", "lagi"],
    ["掉了下来", "diào le xià lái", "fell down", "jatuh"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第10段

    // ===== 第10段 =====
    ["场子", "chǎng zi", "venue", "tempat"],
    ["里", "lǐ", "in", "dalam"],
    ["一片", "yī piàn", "a", "satu"],
    ["喧哗", "xuān huá", "uproar", "kecoh"],
    ["。", "", "", ""],
    ["台上", "tái shàng", "on stage", "di atas pentas"],
    ["，", "", "", ""],
    ["顶碗", "dǐng wǎn", "bowl balancing", "menjunjung mangkuk"],
    ["少年", "shào nián", "youth", "remaja"],
    ["呆呆", "dāi dāi", "blankly", "terpinga-pinga"],
    ["地", "de", "", ""],
    ["站着", "zhàn zhe", "standing", "berdiri"],
    ["，", "", "", ""],
    ["脸上", "liǎn shàng", "face", "muka"],
    ["全是", "quán shì", "all are", "semuanya"],
    ["汗珠", "hàn zhū", "sweat drops", "titisan peluh"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["有些", "yǒu xiē", "somewhat", "agak"],
    ["不知所措", "bù zhī suǒ cuò", "at a loss", "hilang akal"],
    ["了", "le", "", ""],
    ["。", "", "", ""],
    ["还是", "hái shì", "still", "masih"],
    ["那位", "nà wèi", "that", "itu"],
    ["姑娘", "gū niáng", "girl", "gadis"],
    ["，", "", "", ""],
    ["走出来", "zǒu chū lái", "walk out", "keluar"],
    ["扫去", "sǎo qù", "sweep away", "menyapu"],
    ["了", "le", "", ""],
    ["地上", "dì shàng", "ground", "tanah"],
    ["的", "de", "", ""],
    ["碎瓷片", "suì cí piàn", "broken porcelain pieces", "serpihan porselin"],
    ["。", "", "", ""],
    ["观众", "guān zhòng", "audience", "penonton"],
    ["中", "zhōng", "among", "di kalangan"],
    ["有人", "yǒu rén", "someone", "seseorang"],
    ["在", "zài", "in", "di"],
    ["大声", "dà shēng", "loudly", "kuat"],
    ["地", "de", "", ""],
    ["喊", "hǎn", "shout", "jerit"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["行了", "xíng le", "enough", "sudah cukup"],
    ["，", "", "", ""],
    ["不要", "bù yào", "don't", "jangan"],
    ["再", "zài", "again", "lagi"],
    ["来了", "lái le", "come", "datang"],
    ["，", "", "", ""],
    ["演", "yǎn", "perform", "persembahkan"],
    ["下一个", "xià yī gè", "next", "seterusnya"],
    ["节目", "jié mù", "program", "program"],
    ["吧", "ba", "", ""],
    ["。", "", "", ""],
    ["”", "", "", ""],
    ["好多人", "hǎo duō rén", "many people", "ramai orang"],
    ["附和", "fù hè", "echo", "menyokong"],
    ["着", "zhe", "", ""],
    ["喊", "hǎn", "shout", "jerit"],
    ["起来", "qǐ lái", "up", "naik"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第11段

    // ===== 第11段 =====
    ["一位", "yī wèi", "a", "seorang"],
    ["矮小", "ǎi xiǎo", "short", "pendek"],
    ["结实", "jiē shi", "sturdy", "tegap"],
    ["的", "de", "", ""],
    ["白发", "bái fà", "white-haired", "beruban"],
    ["老人", "lǎo rén", "old man", "orang tua"],
    ["从", "cóng", "from", "dari"],
    ["后台", "hòu tái", "backstage", "belakang pentas"],
    ["走到", "zǒu dào", "walk to", "berjalan ke"],
    ["灯光", "dēng guāng", "light", "cahaya"],
    ["下", "xià", "under", "bawah"],
    ["，", "", "", ""],
    ["他", "tā", "his", "dia"],
    ["的", "de", "", ""],
    ["手里", "shǒu lǐ", "hand", "tangan"],
    ["，", "", "", ""],
    ["依然", "yī rán", "still", "masih"],
    ["是", "shì", "is", "ialah"],
    ["一叠", "yī dié", "a stack", "setimbun"],
    ["金边", "jīn biān", "gold-rimmed", "bertepi emas"],
    ["红花", "hóng huā", "red flower", "bunga merah"],
    ["白瓷碗", "bái cí wǎn", "white porcelain bowls", "mangkuk porselin putih"],
    ["！", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["走到", "zǒu dào", "walk to", "berjalan ke"],
    ["少年", "shào nián", "youth", "remaja"],
    ["面前", "miàn qián", "front", "hadapan"],
    ["，", "", "", ""],
    ["脸上", "liǎn shàng", "face", "muka"],
    ["微笑", "wēi xiào", "smile", "senyum"],
    ["着", "zhe", "", ""],
    ["，", "", "", ""],
    ["并无", "bìng wú", "no", "tiada"],
    ["责怪", "zé guài", "blame", "menyalahkan"],
    ["的", "de", "", ""],
    ["神色", "shén sè", "expression", "riak wajah"],
    ["。", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["把", "bǎ", "", ""],
    ["手中", "shǒu zhōng", "hand", "tangan"],
    ["的", "de", "", ""],
    ["碗", "wǎn", "bowls", "mangkuk"],
    ["交给", "jiāo gěi", "hand to", "menyerahkan kepada"],
    ["少年", "shào nián", "youth", "remaja"],
    ["，", "", "", ""],
    ["然后", "rán hòu", "then", "kemudian"],
    ["抚摸", "fǔ mō", "stroke", "mengusap"],
    ["着", "zhe", "", ""],
    ["少年", "shào nián", "youth", "remaja"],
    ["的", "de", "", ""],
    ["肩", "jiān", "shoulder", "bahu"],
    ["，", "", "", ""],
    ["轻轻", "qīng qīng", "gently", "perlahan"],
    ["摇了摇", "yáo le yáo", "shook", "menggoncang"],
    ["，", "", "", ""],
    ["嘴里", "zuǐ lǐ", "mouth", "mulut"],
    ["低声", "dī shēng", "low voice", "suara perlahan"],
    ["说", "shuō", "said", "berkata"],
    ["了", "le", "", ""],
    ["一句", "yī jù", "a sentence", "satu ayat"],
    ["什么", "shén me", "something", "sesuatu"],
    ["。", "", "", ""],
    ["少年", "shào nián", "youth", "remaja"],
    ["镇静", "zhèn jìng", "calm", "tenang"],
    ["下来", "xià lái", "down", "turun"],
    ["，", "", "", ""],
    ["手捧着", "shǒu pěng zhe", "holding", "memegang"],
    ["新碗", "xīn wǎn", "new bowls", "mangkuk baru"],
    ["，", "", "", ""],
    ["又", "yòu", "again", "lagi"],
    ["深深", "shēn shēn", "deeply", "dalam"],
    ["地", "de", "", ""],
    ["向", "xiàng", "to", "kepada"],
    ["观众", "guān zhòng", "audience", "penonton"],
    ["们", "men", "", ""],
    ["鞠了", "jū le", "bowed", "tunduk"],
    ["一躬", "yī gōng", "a bow", "satu tunduk"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第12段

    // ===== 第12段 =====
    ["音乐", "yīn yuè", "music", "muzik"],
    ["第三次", "dì sān cì", "third time", "kali ketiga"],
    ["奏响", "zòu xiǎng", "play", "dimainkan"],
    ["了", "le", "", ""],
    ["！", "", "", ""],
    ["场子", "chǎng zi", "venue", "tempat"],
    ["里", "lǐ", "in", "dalam"],
    ["静得", "jìng de", "so quiet", "begitu senyap"],
    ["没有", "méi yǒu", "no", "tiada"],
    ["一丝", "yī sī", "a trace", "satu"],
    ["声息", "shēng xī", "sound", "bunyi"],
    ["。", "", "", ""],
    ["一些", "yī xiē", "some", "sesetengah"],
    ["女观众", "nǚ guān zhòng", "female audience", "penonton wanita"],
    ["，", "", "", ""],
    ["索性", "suǒ xìng", "simply", "terus"],
    ["捂住", "wǔ zhù", "cover", "menutup"],
    ["了", "le", "", ""],
    ["眼睛", "yǎn jīng", "eyes", "mata"],
    ["……", "", "", ""],

    ["\n", "", "", ""], // 👈 第13段

    // ===== 第13段 =====
    ["这", "zhè", "This", "Ini"],
    ["真是", "zhēn shì", "really is", "benar-benar"],
    ["一场", "yī chǎng", "a", "satu"],
    ["惊心动魄", "jīng xīn dòng pò", "thrilling", "mendebarkan"],
    ["的", "de", "", ""],
    ["拼搏", "pīn bó", "struggle", "perjuangan"],
    ["！", "", "", ""],
    ["当", "dāng", "when", "apabila"],
    ["那叠", "nà dié", "that stack", "setimbun itu"],
    ["碗", "wǎn", "bowls", "mangkuk"],
    ["又", "yòu", "again", "lagi"],
    ["剧烈", "jù liè", "violently", "dengan hebat"],
    ["地", "de", "", ""],
    ["晃动", "huàng dòng", "shake", "bergoyang"],
    ["起来", "qǐ lái", "up", "naik"],
    ["时", "shí", "when", "apabila"],
    ["，", "", "", ""],
    ["少年", "shào nián", "youth", "remaja"],
    ["轻轻", "qīng qīng", "gently", "perlahan"],
    ["抖了", "dǒu le", "shook", "menggoncang"],
    ["一下", "yī xià", "a bit", "sedikit"],
    ["脑袋", "nǎo dai", "head", "kepala"],
    ["，", "", "", ""],
    ["终于", "zhōng yú", "finally", "akhirnya"],
    ["把", "bǎ", "", ""],
    ["碗", "wǎn", "bowls", "mangkuk"],
    ["稳住", "wěn zhù", "stabilize", "menstabilkan"],
    ["了", "le", "", ""],
    ["。", "", "", ""],
    ["全场", "quán chǎng", "whole venue", "seluruh tempat"],
    ["响起", "xiǎng qǐ", "sound", "berbunyi"],
    ["了", "le", "", ""],
    ["暴风雨般", "bào fēng yǔ bān", "like a storm", "seperti ribut"],
    ["的", "de", "", ""],
    ["掌声", "zhǎng shēng", "applause", "tepukan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第14段

    // ===== 第14段 =====
    ["在", "zài", "in", "dalam"],
    ["以后", "yǐ hòu", "later", "kemudian"],
    ["的", "de", "", ""],
    ["岁月", "suì yuè", "years", "tahun-tahun"],
    ["里", "lǐ", "in", "dalam"],
    ["，", "", "", ""],
    ["不知怎的", "bù zhī zěn de", "somehow", "entah bagaimana"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["常常", "cháng cháng", "often", "selalu"],
    ["会", "huì", "will", "akan"],
    ["想起", "xiǎng qǐ", "think of", "teringat"],
    ["这位", "zhè wèi", "this", "ini"],
    ["顶碗", "dǐng wǎn", "bowl balancing", "menjunjung mangkuk"],
    ["少年", "shào nián", "youth", "remaja"],
    ["，", "", "", ""],
    ["想起", "xiǎng qǐ", "think of", "teringat"],
    ["他", "tā", "his", "dia"],
    ["那一次", "nà yī cì", "that one time", "satu kali itu"],
    ["的", "de", "", ""],
    ["演出", "yǎn chū", "performance", "persembahan"],
    ["；", "", "", ""],
    ["而且", "ér qiě", "moreover", "lagipun"],
    ["每每", "měi měi", "every time", "setiap kali"],
    ["想起", "xiǎng qǐ", "think of", "teringat"],
    ["，", "", "", ""],
    ["总会", "zǒng huì", "always will", "sentiasa akan"],
    ["有", "yǒu", "have", "ada"],
    ["一阵", "yī zhèn", "a burst", "satu"],
    ["微微", "wēi wēi", "slight", "sedikit"],
    ["的", "de", "", ""],
    ["激动", "jī dòng", "excitement", "kegembiraan"],
    ["……", "", "", ""],
];

// 如果使用模块导出，取消下一行注释；若通过 script 标签引入，则全局可用
// export { lessonTitle, lessonData };
